apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver
  name: resultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - image: omeryucel02/resultserver
        name: resultserver
        ports:
        - containerPort: 80
        resources: {}
        envFrom:
          - secretRef:
               name: mysql-secret
          - configMapRef:
               name: server-config
